name: deploy-demo
on:
  push:
    branches:
      - 'feature/add_github_actions'
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - 'develop_angular11'
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build:ci
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_docs
          path: docs
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_docs
      - name: Deploy to Github Pages
        uses: h2qutc/angular-material-components@releases/v5.0.2-beta
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
